language: java
before_script: cd 12f_app
script: mvn clean install
deploy:
  edge: true
  provider: cloudfoundry
  username: miket.johnson@sas.com 
  api: https://api.run.pivotal.io
  organization: mitjohorg
  space: mitjohspace